---
title: '1st Assignment'
subtitle: 'Unit Testing'
author:
  name: Hoedt, Mayer, Pfoser (Team 12)
  affiliation: University of Linz
course:
  name: Software Testing
  lvaleiter: Dr. Reinhold Pl√∂sch, Mag. Rudolf Ramler
  institute: Institute of Software Engineering
fontsize: 10pt
...
